CREATE TABLE Agendamento ( id BIGINT AUTO_INCREMENT PRIMARY KEY, 
	id INT AUTO_INCREMENT PRIMARY KEY,
	data DATETIME NOT NULL, 
	nomeUsuario VARCHAR(100) NOT NULL, 
	cpfUsuario VARCHAR(14) NOT NULL, 
	emailUsuario VARCHAR(50) NOT NULL, 
	nomeAdvogado VARCHAR(100) NOT NULL, 
	tipoAtividade VARCHAR(50) NOT NULL,
	primeira_reuniao BOOLEAN NOT NULL DEFAULT TRUE,
	observacao TEXT
)